services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=taskdb;Username=postgres;Password=postgres
      Jwt__Key: dev_only_super_secret_key_1234567890_abcd
      Jwt__Issuer: TaskManagementApi
      Jwt__Audience: TaskManagementApiUsers
      Jwt__ExpiresInMinutes: 60
    ports:
      - "8080:8080"
    volumes:
      - dataprotection_keys:/keys

volumes:
  postgres_data:
  dataprotection_keys: